export const CART_PRODUCT_REQUEST = "CART_PRODUCT_REQUEST"
export const CART_PRODUCT_SUCCESS = "CART_PRODUCT_SUCCESS"
export const CART_PRODUCT_FAILED = "CART_PRODUCT_FAILED"

export const ADD_CART_REQUEST = "ADD_CART_REQUEST"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY"
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY"

export const CLEAR_CART = "CLEAR_CART"